export const MENU_LIST_REQUEST = 'MENU_LIST_REQUEST';
export const MENU_LIST_SUCCESS = 'MENU_LIST_SUCCESS';
export const MENU_LIST_FAIL = 'MENU_LIST_FAIL';

export const MENU_DETAILS_REQUEST = 'MENU_DETAILS_REQUEST';
export const MENU_DETAILS_SUCCESS = 'MENU_DETAILS_SUCCESS';
export const MENU_DETAILS_FAIL = 'MENU_DETAILS_FAIL';

export const MENU_DELETE_REQUEST = 'MENU_DELETE_REQUEST';
export const MENU_DELETE_SUCCESS = 'MENU_DELETE_SUCCESS';
export const MENU_DELETE_FAIL = 'MENU_DELETE_FAIL';

export const MENU_CREATE_REQUEST = 'MENU_CREATE_REQUEST';
export const MENU_CREATE_SUCCESS = 'MENU_CREATE_SUCCESS';
export const MENU_CREATE_FAIL = 'MENU_CREATE_FAIL';
export const MENU_CREATE_RESET = 'MENU_CREATE_RESET';

export const MENU_UPDATE_REQUEST = 'PRODUCT_MENU_REQUEST';
export const MENU_UPDATE_SUCCESS = 'PRODUCT_MENU_SUCCESS';
export const MENU_UPDATE_FAIL = 'PRODUCT_MENU_FAIL';
export const MENU_UPDATE_RESET = 'PRODUCT_MENU_RESET';
