const menus = [
  {
    _id: '1',
    name: 'Breakfast Menu 1',
    image: '/images/breakfast1.jpg',
    description: 'Description Breakfast Menu 1',
    category: 'Breakfast',
    price: 9.99,
    orderCount: 0,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Breakfast Menu 2',
    image: '/images/breakfast2.jpg',
    description: 'Description Breakfast Menu 2',
    category: 'Breakfast',
    price: 5.99,
    orderCount: 0,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Lunch Menu 1',
    image: '/images/lunch1.jpg',
    description: 'Description Lunch Menu 1',
    category: 'Lunch',
    price: 29.99,
    orderCount: 0,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Lunch Menu 2',
    image: '/images/lunch2.jpg',
    description: 'Description Lunch Menu 2',
    brand: 'Sony',
    category: 'Lunch',
    price: 39.99,
    orderCount: 8,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Dinner Menu 1',
    image: '/images/dinner1.jpg',
    description: 'Description Dinner Menu 1',
    brand: 'Logitech',
    category: 'Dinner',
    price: 49.99,
    orderCount: 5,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'Dinner Menu 2',
    image: '/images/dinner2.jpg',
    description: 'Description Dinner Menu 2',
    brand: 'Amazon',
    category: 'Dinner',
    orderCount: 6,
    price: 29.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
];

export default menus;
